### ISSUE TITLE
Completeness of data

### ISSUE THREAD

**Issue by fiddlerwoaroof** [phoe/quicklisp-stats#1]
Looking at the CSV files, it’s not obvious whether the data is complete or if it’s only packages with more than N downloads.

**Comment by phoe** [comment]
AFAIK, the available CSV files only list the top 500 projects. @quicklisp mentioned that they might get updated with the top 1000 projects instead and hoped that there wouldn't be much noise in the resulting tail.

Still, I have no control over the source data - you might want to poke Xach on IRC or make an issue somewhere at @quicklisp.

**Comment by fiddlerwoaroof** [comment]
This should be documented in the readme, I think.

**Comment by phoe** [comment]
Yes. Will do.

**Comment by phoe** [comment]
Done - thanks for the heads-up.
