### ISSUE TITLE
Incorrect URL used for 2021 stats

### ISSUE THREAD

**Issue by Zulu-Inuoe** [phoe/quicklisp-stats#2]
In https://github.com/phoe/quicklisp-stats/blob/29477fafe33a31b09f47d4125e683f7efc40c23a/quicklisp-stats.lisp#L21

We see it always constructs a URL like `https://www.quicklisp.org/stats/2020/YYYY-mm.csv`
But the URL for eg the 2021 csv is actually at https://www.quicklisp.org/stats/2021/2021-01.csv

the `/stats/2020` is not static and is driven by the year

**Comment by phoe** [comment]
Oof. That's a really stupid bug on my side.
Sure, let me fix it.
